openapi: 3.0.0
info:
  title: Knight Social Network
  description: Social network Knight API documentation
  version: 1.0.0
  contact:
    name: Telegram and Discord to contact with me
    url: https://headcrabj.github.io/
  license:
    name: GNU AGPLv3
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
servers:
  - url: http://localhost/
tags:
- name: users
  description: Routes for viewing and managing your account
- name: posts
  description: Routes for viewing and managing your posts
- name: mod
  description: Routes for moderators and admins
paths:
  /users/get:
    get:
      tags:
      - users
      summary: List of users
      description: Returns list of all users in database
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/get/{id}:
    get:
      tags:
      - users
      summary: Get specific user
      description: Returns specified user by id
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        schema:
          type: number
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Bad Request
        404:
          description: User not found
  /users/get/@me:
    get:
      tags:
      - users
      summary: Get current user
      description: Get user by token
      parameters:
      - name: Authorization
        in: header
        description: Discord Access Token
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Bad Request
        404:
          description: User not found
  /users/update/@me:
    put:
      tags:
      - users
      summary: Update current user
      description: Change data in database of current user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      parameters:
      - name: Authorization
        in: header
        description: Discord Access Token
        required: true
        schema:
          type: string
      responses:
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: User not found
  /users/delete/@me:
    delete:
      tags:
      - users
      summary: Delete current user
      description: Delete current user by token from database
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: User not found
  /posts/get:
    get:
      tags:
      - posts
      summary: Get all posts
      description: Returns list of all posts from database
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
  /posts/get/{id}:
    get:
      tags:
      - posts
      summary: Get post by id
      description: Returns post by id
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        schema:
          type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        400:
          description: Bad Request
        404:
          description: Post not found
  /posts/create:
    put:
      tags:
      - posts
      summary: Create post
      description: Create post with content from body
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
              example: Example 1234
      responses:
        400:
          description: String length must be more than 8
        404:
          description: User not found
  /posts/delete/{id}:
    delete:
      tags:
      - posts
      summary: Delete post
      description: Delete post by id
      parameters:
      - name: Authorization
        in: header
        description: Disord Access Token
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: User ID
        required: true
        schema:
          type: integer
      responses:
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: User not found
  /mod/updateTitle/{user}/{title}:
    put:
      tags:
      - mod
      summary: Update title
      description: Update user title
      parameters:
      - name: Authoriozation
        in: header
        description: Discord Access Token
        required: true
        schema:
          type: string
      - name: user
        in: path
        description: User ID
        required: true
        schema:
          type: number
      - name: title
        in: path
        description: User Title
        required: true
        schema:
          type: string
      responses:
        204:
          description: No content
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: User not found
  /mod/clearTitle/{user}:
    delete:
      tags:
      - mod
      summary: Clear title
      description: Clear title of user by id
      parameters:
      - name: Authorization
        in: header
        description: Discord Access Token
        required: true
        schema:
          type: string
      - name: user
        in: path
        description: User ID
        required: true
        schema:
          type: number
      responses:
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: User not found
  /mod/deleteUser/{user}:
    delete:
      tags:
      - mod
      summary: Delete user
      description: Delete user by id
      parameters:
      - name: Authorization
        in: header
        description: Discord Access Token
        required: true
        schema:
          type: string
      - name: user
        in: path
        description: User ID
        required: true
        schema:
          type: number
      responses:
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: User not found

components:
  schemas:
    Title:
      type: string
      enum:
      - GM
      - IM
      - FM
      - CM
      - WGM
      - WIM
      - WFM
      - NM
    Sex:
      type: string
      enum:
      - MALE
      - FEMALE
    Role:
      type: string
      enum:
      - USER
      - MOD
      - ADMIN
    Federation:
      type: string
      enum:
      - FIDE
      - NATIONAL
    Country:
      type: string
      enum:
      - UK
      - US
      - UA
    User:
      type: object
      properties:
        id:
          type: number
          default: "ID from Discord"
          example: 638485831796432456
        name:
          type: string
          default: "Nickname from Discord"
          example: Krabi
        bio:
          type: string
          example: My beautiful bio
        chessLink:
          type: string
          example: https://chess24.com/en/profile/chesshedge
        country:
          type: string
          example: UA
          items:
            $ref: "#/components/schemas/Country"
        email:
          type: string
          example: example@example.com
        federation:
          type: string
          example: "FIDE"
          items:
            $ref: "#/components/schemas/Federation"
        rating:
          type: integer
          default: 0
          example: 32
        role:
          type: string
          example: USER
          default: USER
          items:
            $ref: "#/components/schemas/Role"
        sex:
          type: string
          example: MALE
          items:
            $ref: "#/components/schemas/Sex"
        title:
          type: string
          example: FM
          items:
            $ref: "#/components/schemas/Title"
    Post:
      type: object
      properties:
        id:
          type: number
          example: 56
        date:
          type: number
          example: 1654944238
        author:
          type: number
          example: 638485831796432456
        content:
          type: string
          example: Best post

externalDocs:
  description: GitHub
  url: https://github.com/u032/knight
